# Generated by Django 2.0 on 2019-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gudong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='股东名称')),
                ('own', models.FloatField(verbose_name='所占份额')),
                ('joinday', models.DateField(verbose_name='加入日期')),
                ('latestday', models.DateField(auto_now=True, verbose_name='最近一次信息更新日期')),
            ],
            options={
                'verbose_name': '股东',
                'verbose_name_plural': '股东',
            },
        ),
        migrations.CreateModel(
            name='zhizhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='宠物名称')),
                ('introduce', models.TextField(max_length=2000, verbose_name='宠物简介')),
                ('zhuimage', models.FileField(upload_to='zhizhuimage/', verbose_name='上传一张最能代表它的图片吧')),
            ],
            options={
                'verbose_name': '宠物',
                'verbose_name_plural': '宠物',
            },
        ),
    ]
