# Generated by Django 2.0 on 2019-08-03 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=30, verbose_name='视频名')),
                ('vtype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gongzuoshi.type')),
            ],
        ),
    ]
