# Generated by Django 2.0 on 2019-08-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gongzuoshi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': '视频类别', 'verbose_name_plural': '视频类别'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.AddField(
            model_name='type',
            name='tname',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='vtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gongzuoshi.type', verbose_name='视频分类'),
        ),
    ]
