# Generated by Django 2.0 on 2019-08-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongzuoshi', '0002_auto_20190803_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=30, verbose_name='成员名字')),
                ('job', models.CharField(max_length=30, verbose_name='成员职务')),
                ('jianjie', models.TextField(max_length=200, verbose_name='成员简介')),
            ],
            options={
                'verbose_name': '工作室成员',
                'verbose_name_plural': '工作室成员们',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='vblianjie',
            field=models.CharField(default=None, max_length=50, verbose_name='B站链接'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='vdis',
            field=models.TextField(default=None, max_length=2000, verbose_name='视频描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='videocontent',
            field=models.FileField(default=None, upload_to='gongzuoshi/', verbose_name='上传视频'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='tname',
            field=models.CharField(max_length=20, verbose_name='分类'),
        ),
    ]
