# Generated by Django 2.0 on 2019-08-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongzuoshi', '0003_auto_20190803_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_img',
            field=models.FileField(default='gongzuoshi/imgs/default.png', upload_to='gongzuoshi/imgs/', verbose_name='上传一张视频的封面图片吧！'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vblianjie',
            field=models.CharField(max_length=50, verbose_name="B站链接，如果没有，那就填写'暂无'吧"),
        ),
    ]
