# Generated by Django 2.0 on 2019-08-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qingganpin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=30)),
                ('story', models.TextField(max_length=2000)),
                ('content', models.FileField(upload_to='dayting/')),
            ],
        ),
        migrations.AddField(
            model_name='qingganwen',
            name='topic',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
