# Generated by Django 2.0 on 2019-08-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qingganpin', '0002_auto_20190802_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ting',
            new_name='lisening',
        ),
    ]
