# Generated by Django 2.0 on 2019-08-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qingganpin', '0006_auto_20190829_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lisening',
            options={'ordering': ['date', 'topic'], 'verbose_name': '每月一听歌曲录', 'verbose_name_plural': '每月一听歌曲录'},
        ),
        migrations.AlterModelOptions(
            name='qingganwen',
            options={'ordering': ['date'], 'verbose_name': '情感频文章', 'verbose_name_plural': '情感频文章'},
        ),
    ]
