# Generated by Django 2.0 on 2019-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=2000)),
                ('holder', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='happytime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=30)),
                ('introduction', models.CharField(max_length=500)),
                ('hobby', models.CharField(max_length=500)),
            ],
        ),
    ]
