# Generated by Django 2.0 on 2019-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
