# Generated by Django 2.0 on 2019-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loldata',
            name='location_often',
            field=models.TextField(default='无', max_length=100, verbose_name='常打位置,如果是多个位置用/分隔开'),
        ),
        migrations.AddField(
            model_name='loldata',
            name='max_level',
            field=models.CharField(default='无', max_length=50, verbose_name='最高段位'),
        ),
        migrations.AddField(
            model_name='loldata',
            name='now_level',
            field=models.CharField(default='无', max_length=50, verbose_name='目前段位'),
        ),
        migrations.AlterField(
            model_name='loldata',
            name='hero_often',
            field=models.TextField(default='无', max_length=1000, verbose_name='常用英雄,如果是多个英雄用/分隔开'),
        ),
        migrations.AlterField(
            model_name='loldata',
            name='win_of_all',
            field=models.FloatField(verbose_name='总胜率（将胜率装换为小数输入哦，比如50%则输入0.5）'),
        ),
        migrations.AlterField(
            model_name='loldata',
            name='win_of_paiwei',
            field=models.FloatField(verbose_name='排位胜率（将胜率装换为小数输入哦，比如50%则输入0.5）'),
        ),
        migrations.AlterField(
            model_name='loldata',
            name='win_of_pipei',
            field=models.FloatField(verbose_name='匹配胜率（将胜率装换为小数输入哦，比如50%则输入0.5）'),
        ),
    ]
