# Generated by Django 2.0 on 2019-07-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190724_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='mimage',
            field=models.FileField(default=None, upload_to='memberimage/'),
            preserve_default=False,
        ),
    ]
