# Generated by Django 2.0 on 2019-08-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190828_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loldata',
            name='date_latest',
            field=models.DateTimeField(auto_now=True, verbose_name='数据更新时间'),
        ),
    ]
