# Generated by Django 2.0 on 2019-07-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_members_mimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='happytime',
            name='himage',
            field=models.FileField(default=None, upload_to='happyimage/'),
            preserve_default=False,
        ),
    ]
