# Generated by Django 2.0 on 2019-07-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_happytime_himage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happytime',
            name='hid',
            field=models.CharField(max_length=30),
        ),
    ]
