# Generated by Django 2.0 on 2019-08-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190730_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '经典活动', 'verbose_name_plural': '经典活动'},
        ),
        migrations.AlterModelOptions(
            name='happytime',
            options={'verbose_name': '开心时光', 'verbose_name_plural': '开心时光'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': '成员', 'verbose_name_plural': '成员'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='holder',
            field=models.CharField(max_length=20, verbose_name='主持人'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='活动内容'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='topic',
            field=models.CharField(max_length=30, verbose_name='活动主题'),
        ),
        migrations.AlterField(
            model_name='happytime',
            name='author',
            field=models.CharField(max_length=30, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='happytime',
            name='hid',
            field=models.CharField(max_length=30, verbose_name='时光代号'),
        ),
        migrations.AlterField(
            model_name='happytime',
            name='himage',
            field=models.FileField(upload_to='happyimage/', verbose_name='上传一张最具代表性的图片吧'),
        ),
        migrations.AlterField(
            model_name='happytime',
            name='text',
            field=models.CharField(max_length=2000, verbose_name='时光内容'),
        ),
        migrations.AlterField(
            model_name='happytime',
            name='title',
            field=models.CharField(max_length=30, verbose_name='时光主题'),
        ),
        migrations.AlterField(
            model_name='members',
            name='hobby',
            field=models.CharField(max_length=500, verbose_name='成员爱好'),
        ),
        migrations.AlterField(
            model_name='members',
            name='introduction',
            field=models.CharField(max_length=500, verbose_name='成员简介'),
        ),
        migrations.AlterField(
            model_name='members',
            name='mid',
            field=models.CharField(max_length=30, verbose_name='成员ID'),
        ),
        migrations.AlterField(
            model_name='members',
            name='mimage',
            field=models.FileField(upload_to='memberimage/', verbose_name='上传一张最具代表性的图片吧'),
        ),
    ]
