# Generated by Django 2.0 on 2019-08-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190803_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='introduction',
            field=models.TextField(max_length=500, verbose_name='成员简介'),
        ),
    ]
